# Generated by the prpr release workflow; changes here are overwritten.
class Prpr < Formula
  desc "Terminal app for monitoring your open GitHub pull requests and review requests"
  homepage "https://github.com/DragosMocrii/prpr"
  version "0.1.37"
  license "MIT"

  depends_on "gh"

  on_macos do
    on_arm do
      url "https://github.com/DragosMocrii/prpr/releases/download/v0.1.37/prpr_0.1.37_darwin_arm64.tar.gz"
      sha256 "c2ea5af9a34a87554b091d888465d5ee773a6f98e6389d8c86ce1fd0da21595d"
    end
    on_intel do
      url "https://github.com/DragosMocrii/prpr/releases/download/v0.1.37/prpr_0.1.37_darwin_amd64.tar.gz"
      sha256 "66cb00bde75f59e737b6a1bc0682b28e54aea0bf3503889a64de31a26885ed8b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/DragosMocrii/prpr/releases/download/v0.1.37/prpr_0.1.37_linux_arm64.tar.gz"
      sha256 "03fc2520573b1451d1243e789da653bced93a22ba505d42a79198f6dc6390273"
    end
    on_intel do
      url "https://github.com/DragosMocrii/prpr/releases/download/v0.1.37/prpr_0.1.37_linux_amd64.tar.gz"
      sha256 "a4e5df740a99958b4fb91228d9f50dde162f4926bceeeec3b85815fdf94e4773"
    end
  end

  def install
    bin.install "prpr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/prpr --version")
  end
end
