# Generated by the prpr release workflow; changes here are overwritten.
class Prpr < Formula
  desc "Terminal app for monitoring your open GitHub pull requests and review requests"
  homepage "https://github.com/DragosMocrii/prpr"
  version "0.1.38"
  license "MIT"

  depends_on "gh"

  on_macos do
    on_arm do
      url "https://github.com/DragosMocrii/prpr/releases/download/v0.1.38/prpr_0.1.38_darwin_arm64.tar.gz"
      sha256 "fb875425a83fde8d30b94299d588d9f0efbe3883d8541215fe3b4515a4be1a12"
    end
    on_intel do
      url "https://github.com/DragosMocrii/prpr/releases/download/v0.1.38/prpr_0.1.38_darwin_amd64.tar.gz"
      sha256 "6e37c48254fdd3bbce85c0f4eae9c3065c37854ef42663b0d3c89938dc6d1b24"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/DragosMocrii/prpr/releases/download/v0.1.38/prpr_0.1.38_linux_arm64.tar.gz"
      sha256 "0efbc646a3c3528dd38fb085aaf0fda05eb27f965a7e68a28a1ec112d1c0f705"
    end
    on_intel do
      url "https://github.com/DragosMocrii/prpr/releases/download/v0.1.38/prpr_0.1.38_linux_amd64.tar.gz"
      sha256 "95819060df9500e8ac20b0c2084bd33ae2b0c9eaaf25f6d158bbae1e758a108b"
    end
  end

  def install
    bin.install "prpr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/prpr --version")
  end
end
