# Generated by the prpr release workflow; changes here are overwritten.
class Prpr < Formula
  desc "Terminal app for monitoring your open GitHub pull requests and review requests"
  homepage "https://github.com/DragosMocrii/prpr"
  version "0.1.17"
  license "MIT"

  depends_on "gh"

  on_macos do
    on_arm do
      url "https://github.com/DragosMocrii/prpr/releases/download/v0.1.17/prpr_0.1.17_darwin_arm64.tar.gz"
      sha256 "3b588d233a1bd5ad66f418f689b2dbaecd71741c161ed5b9fe418e7a1bd9ef88"
    end
    on_intel do
      url "https://github.com/DragosMocrii/prpr/releases/download/v0.1.17/prpr_0.1.17_darwin_amd64.tar.gz"
      sha256 "403dc001a849854262216333884fb827b1f8315f6377cb6b23e5e240d0761fc5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/DragosMocrii/prpr/releases/download/v0.1.17/prpr_0.1.17_linux_arm64.tar.gz"
      sha256 "9348bda538cd27d93855caf8f90511cabe4b1cfcdc0594c61bc7c98fe4130825"
    end
    on_intel do
      url "https://github.com/DragosMocrii/prpr/releases/download/v0.1.17/prpr_0.1.17_linux_amd64.tar.gz"
      sha256 "c4a5283ad5a6ad15256d24505c73e561465c326411607b4c80d3929900550e8c"
    end
  end

  def install
    bin.install "prpr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/prpr --version")
  end
end
